Feature/baw 8/0
iOS-vk-education/2024_1_BecomeAWind pull request #10
Opened 2024-11-16 13:39 UTC by ilyansky

- Изменил podfile
- Добавил таб бар.
- Настроил навигацию в приложении.
- Добавил карту, функцию определения локации

2024-11-16 15:28 UTC, gp8stvlv commented on Yam/Yam/MapViewModel.swift
> +    static let span = MKCoordinateSpan(latitudeDelta: 0.01, longitudeDelta: 0.01)
а для чего в названии Delta?

2024-11-16 15:30 UTC, gp8stvlv commented on Yam/Yam/MapViewModel.swift
> +                print("Show alert to enable location services")
потом в этом месте собираешься вывод алерта добавить? 
если да , то заведи задачку , и подпиши условно 
// TODO: и номер задачи

2024-11-16 16:16 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +                print("Show alert to enable location services")
Понял

2024-11-16 19:41 UTC, blackplayerten requested changes
посмотреть как правильно выносить отдельные ui компоненты

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam.xcodeproj/xcuserdata/terabrim.xcuserdatad/xcschemes/xcschememanagement.plist
этот файл должен быть в гитигноре

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    static let startingLocation = CLLocationCoordinate2D(latitude: 55.751188, longitude: 37.627939)
defaultLocation
такую константу лучше вынести в Mock данные

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +final class MapViewModel: NSObject, ObservableObject, CLLocationManagerDelegate {
вынести NSObject и CLLocationManagerDelegate в экстеншн

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +                self.locationManager?.delegate = self
вынести в функцию initLocationManager()

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +            return
нужен алерт с ошибкой (в туду пока)

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +        withAnimation {
это не здесь писать, а во view

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +            )
можно в 1 строку это написать

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +        guard let locationManager = locationManager else { return }
ошибку возвращать

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/MainView.swift
> +struct MainView: View {
переименовать
это таббар? если да, то TabBarView

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/MainView.swift
> +    }
раз ты оставил комментарии views, tab bar, значит, сам запутался, что где отображается
мне тоже если честно не очень понятно)
кажется, это надо как-то разделить

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/TabBarView.swift
> +enum Tab: String, CaseIterable {
TabImage?
можно сделать приватными в самом таббаре

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/TabBarView.swift
> +    var itemSize: CGFloat = 50
private

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/TabBarView.swift
> +    var body: some View {
отступ

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    func checkIfLocationServicesIsEnabled() {
добавить протокол и вынести в экстеншн

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    var locationManager: CLLocationManager?
private? private(set)?

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +            print("Your location is restricted")
завести енамы (разные) с ошибками карты/интернета и тд

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    @Published var region = MKCoordinateRegion(
currentLocation и в 1 строку

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    func checkIfLocationServicesIsEnabled() {
это проверка сервисов с дальнейшей возможностью их включить (было бы логично), а значит, нужно назвать requestLocationServices() -> Bool 
по этому булу во вью можно отрисовать ошибку или наоборот что-то, что показывает пользователю, что локация включена

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/View/MapView.swift
> +                            viewModel.changeRegion()
тогда setCurrentLocation

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    func changeRegion() {
setCurrentLocation

2024-11-16 19:41 UTC, blackplayerten commented on Yam/Yam/MapViewModel.swift
> +    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
нигде не вызывается

2024-11-16 20:09 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
Эта функция делегата CLLocationManagerDelegate. Она вызывается каждый раз когда создается объект класса CLLocationManager.

https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/locationmanagerdidchangeauthorization(_:)

2024-11-16 20:10 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +    func changeRegion() {
+

2024-11-16 20:10 UTC, ilyansky commented on Yam/Yam/View/MapView.swift
> +                            viewModel.changeRegion()
+

2024-11-16 20:15 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +    func checkIfLocationServicesIsEnabled() {
+

2024-11-25 20:28 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +    func checkIfLocationServicesIsEnabled() {
+

2024-11-26 09:14 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +                self.locationManager?.delegate = self
+

2024-12-18 17:37 UTC, ilyansky commented on Yam/Yam.xcodeproj/xcuserdata/terabrim.xcuserdatad/xcschemes/xcschememanagement.plist
+

2024-12-19 21:13 UTC, ilyansky commented on Yam/Yam/MapViewModel.swift
> +                self.locationManager?.delegate = self
done

2024-12-29 17:32 UTC, blackplayerten approved these changes
замечания в ветке рк2

2025-03-25 18:22 UTC, closed without merging