BAW-4: Запушить проект
iOS-vk-education/2024_1_BecomeAWind pull request #2
Opened 2024-10-27 09:54 UTC by ilyansky

Cоздать проект

2024-10-28 14:10 UTC, blackplayerten requested changes

2024-10-28 14:10 UTC, blackplayerten commented on .gitignore
> +.DS_Store
можно сформировать на gitignore.io и прописать там еще macos, swift, xcode, swift и тд

также файлы с xc*, объявленные ниже туда же

2024-10-28 14:29 UTC, ilyansky commented on .gitignore
> +.DS_Store
Понял про gitignore.io

2024-10-28 15:11 UTC, gp8stvlv commented on .gitignore
> +.DS_Store
вроде есть сайтик , который gitignore для swift проектов генерит , можешь попробовать поискать

2024-10-28 15:25 UTC, ilyansky commented on .gitignore
> +.DS_Store
Я понял, я уже сгенерил. Но я не понял это -  "также файлы с xc*, объявленные ниже туда же". Что от меня здесь требуется?

2024-10-30 15:49 UTC, gp8stvlv approved these changes

2024-10-30 15:49 UTC, merged