README.md
iOS-vk-education/2024_1_BecomeAWind pull request #3
Opened 2024-10-29 22:01 UTC by arsikbarsik123

2024-10-30 08:14 UTC, gp8stvlv commented on README.md
> +1. https://github.com/blackplayerten - Курганова Александра, ментор команды
думаю наши гитхабы не нужны)

2024-10-30 08:15 UTC, gp8stvlv commented on README.md
> +
пустые лишние строки можно убрать

2024-10-30 15:41 UTC, gp8stvlv commented
поменять название МРа

2024-10-30 15:43 UTC, gp8stvlv commented on README.md
> +
и 30.10 сегодня 
жду тогда ссылку актуальную:)

2024-10-30 15:44 UTC, gp8stvlv commented on README.md
> +Ссылка на общий проект фигмы: пупупу его пока нет, будет создан 30.10
это же сегодня:) жду тогда

2024-10-31 15:07 UTC, blackplayerten requested changes

2024-10-31 15:07 UTC, blackplayerten commented on README.md
Не хватает ссылки на таск-трекер

2024-11-01 19:24 UTC, gp8stvlv commented
название МРа все еще не то
нужно взять title задачи с доски

2024-11-04 14:26 UTC, gp8stvlv commented
название мра

2024-11-07 21:35 UTC, blackplayerten approved these changes

2024-11-08 17:10 UTC, merged